import { Court } from '@/types/courts';
import { Event, EventVisibility, EventJoinPolicy, EventHostType, EventBookingMode } from '@/types/event';
import { User, OnboardingStatus } from '@/types/user';
import { Club } from '@/types/club';

export const mockUser: User = {
  id: '1',
  email: 'john.doe@example.com',
  first_name: 'John',
  last_name: 'Doe',
  created_at: new Date().toISOString(),
  over_18: true,
  onboarding_status: OnboardingStatus.COMPLETED,
};

export const mockCourts: Court[] = [
  {
    id: '1',
    name: 'Central Park Basketball Court',
    description: 'A popular outdoor basketball court located in the heart of Central Park. Features full court with lighting for evening games.',
    location: {
      latitude: 40.7829,
      longitude: -73.9654,
      geohash: '',
      address: '1 Central Park, New York, NY 10023',
    },
    images: [
      'https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1080882/pexels-photo-1080882.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    tags: ['Outdoor', 'Full Court', 'Lighting', 'Free'],
    checked_in_users: ['1', '2'],
    followers: ['1', '2', '3'],
    created_by: '1',
    created_at: new Date().toISOString(),
    rating: 4.5,
    reviews: [],
    opening_hours: {
      always_open: true,
      monday: { always_open: true, open_time: '', close_time: '' },
      tuesday: { always_open: true, open_time: '', close_time: '' },
      wednesday: { always_open: true, open_time: '', close_time: '' },
      thursday: { always_open: true, open_time: '', close_time: '' },
      friday: { always_open: true, open_time: '', close_time: '' },
      saturday: { always_open: true, open_time: '', close_time: '' },
      sunday: { always_open: true, open_time: '', close_time: '' },
    },
    verified: true,
  },
  {
    id: '2',
    name: 'Brooklyn Bridge Park Courts',
    description: 'Scenic half-court basketball courts with stunning waterfront views. Perfect for casual games and pickup matches.',
    location: {
      latitude: 40.7009,
      longitude: -73.9969,
      geohash: '',
      address: '334 Furman St, Brooklyn, NY 11201',
    },
    images: [
      'https://images.pexels.com/photos/1080882/pexels-photo-1080882.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    tags: ['Outdoor', 'Half Court', 'Waterfront View'],
    checked_in_users: ['3'],
    followers: ['1', '4'],
    created_by: '2',
    created_at: new Date().toISOString(),
    rating: 4.2,
    reviews: [],
    opening_hours: {
      always_open: true,
      monday: { always_open: true, open_time: '', close_time: '' },
      tuesday: { always_open: true, open_time: '', close_time: '' },
      wednesday: { always_open: true, open_time: '', close_time: '' },
      thursday: { always_open: true, open_time: '', close_time: '' },
      friday: { always_open: true, open_time: '', close_time: '' },
      saturday: { always_open: true, open_time: '', close_time: '' },
      sunday: { always_open: true, open_time: '', close_time: '' },
    },
    verified: false,
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    name: '3v3 Tournament',
    description: 'Competitive 3v3 basketball tournament. Winner takes all!',
    start_date: new Date(Date.now() + 86400000).toISOString(),
    end_date: new Date(Date.now() + 86400000 + 3600000).toISOString(),
    is_online: false,
    address: null,
    latitude: null,
    longitude: null,
    geohash: null,
    visibility: EventVisibility.PUBLIC,
    join_policy: EventJoinPolicy.OPEN,
    max_participants: 12,
    is_cancelled: false,
    created_by_user_id: '1',
    host_type: EventHostType.USER,
    society_id: null,
    university_id: null,
    banner_image_url: null,
    booking_mode: EventBookingMode.FREE,
    price_from: null,
    currency: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Free Pickup Games',
    description: 'Casual pickup games every Sunday. All skill levels welcome!',
    start_date: new Date(Date.now() + 259200000).toISOString(),
    end_date: new Date(Date.now() + 259200000 + 7200000).toISOString(),
    is_online: false,
    address: null,
    latitude: null,
    longitude: null,
    geohash: null,
    visibility: EventVisibility.PUBLIC,
    join_policy: EventJoinPolicy.OPEN,
    max_participants: 20,
    is_cancelled: false,
    created_by_user_id: '2',
    host_type: EventHostType.USER,
    society_id: null,
    university_id: null,
    banner_image_url: null,
    booking_mode: EventBookingMode.FREE,
    price_from: null,
    currency: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'NYC Ballers',
    description: 'Premier basketball club in New York City. We focus on skill development and competitive play.',
    logo: 'https://images.pexels.com/photos/1080882/pexels-photo-1080882.jpeg?auto=compress&cs=tinysrgb&w=400',
    admin_id: '1',
    members: ['1', '2', '3', '4', '5'],
    training_schedule: [
      {
        id: '1',
        title: 'Skills Training',
        court_id: '1',
        start_time: new Date(Date.now() + 86400000),
        end_time: new Date(Date.now() + 86400000 + 3600000),
        max_participants: 15,
        current_participants: 10,
        price: 20,
        recurring_days: ['Monday', 'Wednesday', 'Friday'],
      },
    ],
    court_ids: ['1'],
    fees: {
      monthly: 150,
      session: 20,
    },
    created_at: new Date(),
  },
];